### PR TITLE
Update templates for 2022.10.4 release

### PR DESCRIPTION
**Pull request by andreidorin-oprea**
Update templates for the latest release:
- Use S3 for Automation Suite object storage instead of in-cluster storage. Remove unnecessary disk as a result.
- Add retry logic for enabling the backup to avoid transient issues;
- Fix typo in `init-disk`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sshvans — DISMISSED** [review]

**Comment by andreidorin-oprea** [comment]
@sshvans did the e2e tests finish?

**Comment by sshvans** [comment]
@andreidorin-oprea It failed due to version mismatch in the .taskcat.yml file and main.template. Running it again with updated version.

**Comment by andreidorin-oprea** [comment]
> @andreidorin-oprea It failed due to version mismatch in the .taskcat.yml file and main.template. Running it again with updated version.

Missed that. Thank you @sshvans for fixing it! Please let me know the result for the rerun.

**Review by sshvans — APPROVED** [review]

**Pull request merged**
